Django Practise/My_First_Project/My_First_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),

]

Django Practise/My_First_Project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('album_form/', views.album_form, name='album_form'),
    path('musician_form/', views.musician_form, name='musician_form'),
    path('album_list/<int:artist_id>', views.album_list, name='album_list'),
    path('edit_artist/<int:artist_id>', views.edit_artist, name='edit_artist'),
    path('edit_album/<int:album_id>', views.edit_album, name='edit_album'),
]

Django Practise/My_First_Project/first_app/models.py
from django.db import models

# Create your models here.

class Musician(models.Model):
    # id = models.AutoField(Primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Album(models.Model):
    # id = models.AutoField(Primary_key=True)
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField()

    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Excellent"),
    )
    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name

Django Practise/My_First_Project/first_app/forms.py
from django import forms
from first_app import models

class MusicianForm(forms.ModelForm):
    class Meta(object):
        model = models.Musician
        fields = "__all__"

class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta(object):
        model = models.Album
        fields = "__all__"

Django Practise/My_First_Project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Musician, Album
from first_app import forms
from django.db.models import Avg

# Create your views here.
def index(request):
    musician_list = Musician.objects.order_by('first_name')
    album_list = Album.objects.order_by('name')
    diction = {'title' : "Home Page", 'musician_list':musician_list, 'album_list':album_list}
    return render(request, 'first_app/index.html', context=diction)

def album_list(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    album_list = Album.objects.filter(artist=artist_id).order_by('name')
    artist_rating = Album.objects.filter(artist=artist_id).aggregate(Avg('num_stars'))

    diction = {'title' : "List of Albums", 'artist_info':artist_info, 'album_list':album_list, 'artist_rating':artist_rating}
    return render(request, 'first_app/album_list.html', context=diction)

# ---------------------------------------------
# SQL: SELECT * FROM Musician
# Django Query: Musician.objects.all()
# ---------------------------------------------
# SQL: SELECT * FROM Musician WHERE id=1
# Django Query: Musician.objects.get(pk=1)
# ---------------------------------------------
# SQL: SELECT * FROM Album WHERE artist_id=1
# Django Query: Album.objects.filter(artist_id=1)
# ---------------------------------------------

def musician_form(request):
    form = forms.MusicianForm()

    if request.method == 'POST':
        form = forms.MusicianForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title' : "Add Musician", 'musician_form':form}
    return render(request, 'first_app/musician_form.html', context=diction)

def album_form(request):
    form = forms.AlbumForm()

    if request.method == 'POST':
        form = forms.AlbumForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction = {'title' : "Add Album",'album_form':form}
    return render(request, 'first_app/album_form.html', context=diction)

def edit_artist(request,artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    form = forms.MusicianForm(instance=artist_info)

    if request.method == 'POST':
        form = forms.MusicianForm(request.POST,instance=artist_info)

        if form.is_valid():
            form.save(commit=True)
            return album_list(request,artist_id)

    diction = {'edit_form':form}
    return render(request, 'first_app/edit_artist.html', context=diction)

def edit_album(request,album_id):
    album_info = Album.objects.get(pk=album_id)
    form = forms.AlbumForm(instance=album_info)

    if request.method == 'POST':
        form = forms.AlbumForm(request.POST,instance=album_info)

        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text':'Album Successfully Updated'})
    
    diction.update({'edit_form':form})
    return render(request, 'first_app/edit_album.html', context=diction)

Django Practise/My_First_Project/templates/first_app/album_form.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
<h1>Album Form</h1>
<form method="post">
  {{ album_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Add Album" class="btn btn-primary btn-sm">
</form>
{% endblock %}

Django Practise/My_First_Project/templates/first_app/album_list.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
<h1>Album List</h1>
<h4>Artist Name: {{artist_info.first_name}} {{artist_info.last_name}} </h4>
<h4>Instrument Name: {{artist_info.instrument}} </h4>
<h4>Artist Rating: {{artist_rating.num_stars__avg}} </h4>
<hr>

<a href="{% url 'first_app:edit_artist' artist_id=artist_info.id %}" class="btn btn-primary btn-sm">Edit</a>
<table class="table table-bordered">
  <tr>
    <th>Album Name: </th>
    <th>Release Date: </th>
    <th>Rating: </th>
  </tr>
  <tr>
    <td> <a href="{% url 'first_app:edit_album' album_id=album.id %}">{{ album.name }}</a></td>
    <td>{{ album.release_date }}</td>
    <td>{{ album.num_stars }}</td>
  </tr>
</table>
{% endblock %}

Django Practise/My_First_Project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'first_app:index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'first_app:musician_form' %}">Add Musician</a>
            <a class="nav-item nav-link" href="{% url 'first_app:album_form' %}">Add Album</a>
      </div>
    </nav>

    {% block body_block %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

Django Practise/My_First_Project/templates/first_app/edit_album.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<h3>Edit Album</h3>

{% if success_text %}
  <div class="alert alert-success">
    {{ success_text }}
  </div>
{% endif %}

<form method="POST">
  {{ edit_album.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
</form>
{% endblock %}

Django Practise/My_First_Project/templates/first_app/edit_artist.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<h3>Edit Artist</h3>
<form method="POST">
  {{ edit_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Update" class="btn btn-info btn-sm">
</form>

{% endblock %}

Django Practise/My_First_Project/templates/first_app/form.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% block body_block %}
<h1>This is Form Page</h1>
{% endblock %}

Django Practise/My_First_Project/templates/first_app/index.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
<h1>Home Page</h1>

<h2>Musicians</h2>
<ul>
  {% if musician_list %}

  {% for musician in musician_list %}
    <li> <a href="{% url 'first_app:album_list' artist_id:musician_id %}">{{ musician.first_name}} {{ musician.last_name}}</a> </li>
  {% endfor %}
  {% else %}
    <h3>No Musicians yet</h3>
  {% endif%}
</ul>

<h2>Albums</h2>
<ul>
  {% if album_list %}

  {% for album in album_list %}
    <li>{{ album.artist}}, {{ album.name}}, {{ album.release_date}}, {{ album.num_stars}}</li>
  {% endfor %}
  {% else %}
    <h3>No Album yet</h3>
  {% endif%}
</ul>

{% endblock %}

Django Practise/My_First_Project/templates/first_app/musician_form.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}

{% block body_block %}
<h1>Musician Form</h1>
<form method="post">
  {{ musician_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Add Musician" class="btn btn-primary btn-sm">
</form>
{% endblock %}